# Generated by Django 6.0.5 on 2026-06-26 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('NOTEBOOK', 'Notebooks'), ('COMPUTADOR', 'Computadores'), ('PERIFERICO', 'Perifericos'), ('COMPONENTE', 'Componentes'), ('MONITOR', 'Monitores'), ('ARMAZENAMENTO', 'Armazenamento'), ('REDE', 'Redes'), ('ACESSORIO', 'Acessorios'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='garantia_meses',
            field=models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
